-- © 2026 Exocortex contributors. Licence: MIT. See LICENSE-CODE.
-- schema/34_capture_content_hash.sql — content_hash for Capture API upsert.
--
-- Why: /capture's INSERT ... ON CONFLICT (tenant_id, source_type, uri) DO
-- NOTHING meant a changed file at an already-known uri silently never
-- updated raw_sources.metadata and never fired pg_notify — a re-edited
-- meeting note, RSS article, or vault-note was invisible to every
-- processor forever after its first capture. Found building the F34
-- meeting-ingest refactor: the old workers/ingest.py detects content
-- changes via a body hash and re-processes; the canonical Capture-API
-- path had no equivalent, and this affects every source_type, not just
-- meeting notes.
--
-- Why a GENERATED column instead of computing the hash in capture_api.py:
-- raw_payload is NOT present on every raw_sources row (notion-task-sync,
-- gmail-thread, generated-frp never set it — confirmed by reading every
-- capture-triggering call site, not assumed) and generated-frp bypasses
-- capture_api.py entirely with a direct SQL INSERT. A Python-computed
-- hash would silently miss that path; a generated column is computed by
-- Postgres regardless of how the row got written, so there is exactly one
-- place this can ever be wrong. Hashing the whole `metadata` JSONB (not
-- just raw_payload) also means sources whose "content" IS their metadata
-- (Notion page properties, email snippets) still get real change
-- detection instead of a permanently-null hash.
--
-- Scope note on "no full text — copyright requirement" (01_base.sql:7,17):
-- that comment is about not STORING third-party content bytes in this
-- table; it was never about hashes. A hash is one-way — it doesn't
-- reconstitute the source text, so it was never in scope of the concern
-- it documents. Left 01_base.sql itself untouched (already-applied
-- migration, hash-tracked); this comment is the clarification.
--
-- Separately, and NOT addressed by this migration: metadata.raw_payload
-- already stores up to 64KB of raw content today for most source_types
-- INCLUDING copyrighted third-party ones (rss-frp, arxiv, newsletter) —
-- a real gap between that documented intent and current behaviour. Not
-- this migration's concern; tracked as a separate open
-- question.
--
-- Why `metadata - 'processors'` and not plain `metadata`: processors
-- write their own completion stamp back into this same column
-- (processors/_common.py::mark_processed sets metadata.processors[name]
-- after a run). That stamp is never part of an incoming /capture payload.
-- Hashing the whole column meant that once any processor had stamped a
-- row, the *next* identical re-POST looked "changed" (EXCLUDED.metadata,
-- built fresh from the request, lacks the stamp the stored row now
-- carries) — silently wiping the stamp and re-notifying on every cycle,
-- exactly the reprocessing-storm this migration exists to prevent. Caught
-- by test_unchanged_repost_does_not_update_or_reprocess. Excluding the
-- `processors` key makes the hash reflect only capture-payload-derived
-- content, which is the only thing "changed" should ever mean here.

ALTER TABLE raw_sources ADD COLUMN IF NOT EXISTS content_hash TEXT
    GENERATED ALWAYS AS (md5((metadata - 'processors')::text)) STORED;

COMMENT ON COLUMN raw_sources.content_hash IS
    'F34 — md5 of (metadata - processors)::text, generated by Postgres on '
    'every write regardless of insert path. The processors key is excluded '
    'because it is a downstream completion stamp, not capture content — '
    'see the migration file comment. Drives /capture''s conditional '
    'UPDATE: a re-POST at an existing uri only touches the row (and only '
    're-notifies downstream processors) when this actually differs from '
    'the incoming value — an unchanged re-POST is a true no-op, not a '
    'queue-filler.';
