# © 2026 Eryk Orłowski and Exocortex contributors.
# Licensed under Apache 2.0 + Commons Clause. See LICENSE for details.

"""Shared helpers for loading user-customisable YAML configs.

The convention adopted in F31.8.4 splits ``config/`` files into two cohorts:

* **Shipped defaults** (e.g. ``tag_taxonomy.yaml``, ``llm_routing.yaml``,
  ``wiki_schema.yaml``) — committed in the repo, loaded directly by their
  modules. No example/fallback needed because the file is always present.

* **User-customisable** (e.g. ``projects.yaml``, ``sources.yaml``,
  ``auto_tag_taxonomy.yaml``, ``news_topic_clusters.yaml``,
  ``work_tag_clusters.yaml``) — only an ``X.example.yaml`` is committed; the
  real ``X.yaml`` is gitignored and created by ``exocortex init`` (or by hand
  via ``cp X.example.yaml X.yaml``). The loaders below transparently fall back
  to the example file in fresh checkouts so unit tests and ``--help`` don't
  blow up before init has run.

The :func:`resolve_config_path` helper returns the path that should be opened
by the caller (real file if present, example otherwise). The caller is
responsible for whatever parsing it needs to do — this module deliberately
does not import ``yaml`` so it stays usable from stub-heavy test contexts.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parent.parent

# Files in this set are gitignored when copied to their non-example form and
# generated by ``exocortex init``. Keep this list in sync with ``.gitignore``
# and ``exocortex.init_cmd._USER_YAML_FILES``.
USER_YAML_FILES: tuple[str, ...] = (
    "projects.yaml",
    "sources.yaml",
    "auto_tag_taxonomy.yaml",
    "news_topic_clusters.yaml",
    "work_tag_clusters.yaml",
    "integrations.yaml",
    "graph_rag.yaml",
)


def resolve_config_path(name: str, config_dir: Path | None = None) -> Path:
    """Return the path to load for a given config file name.

    Prefers ``config/<name>``; falls back to ``config/<stem>.example.<ext>``
    if the user-specific copy doesn't exist yet (fresh checkout pre-init).
    Returns the real path even when it does not exist on disk, so callers can
    surface a clean FileNotFoundError to the user rather than a silent miss.

    Args:
        name: filename relative to ``config/``, e.g. ``"projects.yaml"``.
            Must be a bare filename — separators (``/``, ``\\``, ``..``) are
            rejected so a caller cannot escape ``config/`` via the lookup.
        config_dir: override for tests; defaults to ``<repo>/config``.

    Returns:
        Path object. May or may not exist; check ``.exists()`` if needed.

    Raises:
        ValueError: if ``name`` contains a path separator or is empty.
    """
    # Reject anything that isn't a bare filename. Path("foo/bar").name is
    # "bar" on POSIX; Path("..\\foo").name is "..\\foo" on POSIX because
    # backslash is a legal char there — so we additionally forbid both
    # separators explicitly to keep the contract identical cross-platform.
    if not name or "/" in name or "\\" in name or Path(name).name != name:
        raise ValueError(
            f"resolve_config_path expects a bare filename, got {name!r}"
        )
    base = (config_dir or (REPO_ROOT / "config")).resolve()
    real = base / name
    if real.exists():
        return real
    # ``projects.yaml`` -> ``projects.example.yaml``
    p = Path(name)
    example = base / f"{p.stem}.example{p.suffix}"
    if example.exists():
        logger.debug(
            "Loading %s from example fallback %s (run `exocortex init` to "
            "create your own copy)",
            name,
            example.name,
        )
        return example
    # Neither exists; return the canonical path so callers get a clear error.
    return real
